### ISSUE TITLE
docs: add good practices to readme.me

### ISSUE THREAD

**Issue by DanielDerma** [EstandaresDeCalidadSW23/vikingos-analyser#19] opened 2023-09-02 17:47 UTC
Usar prefijos para tus commits, pr y tickets. para hacerlos más semánticos
use prefix for your commits, pr and tickets, make them more sematics
ie:
```
feat: add new search feature
^--^  ^--------------------^
│     │
│     └--> # Descripción de los cambios
│
└──------> # Tipo del cambio
```

```
feat(backend): add filter for cars
fix(web): remove wrong color
```

**Comment by bcisneros** [comment] 2023-09-02 22:26
@DanielDerma is this a duplicate of #18? If that is the case please close this ticket or reuse it for another task.

**Comment by bcisneros** [comment] 2023-09-03 22:29
It is up to the team, but I suggest including the ticket number as a reference

```
feat(moduleXYZ): #123 Adding feature ABC to module XYZ
```

**Closed as completed** 2023-09-09 15:13 UTC
Labels: documentation
